/**
 * 공고 목록 필터 상수 — BUDGET_PRESETS / REGION_GROUPS / RegionItem
 * (announcements/page.tsx 의 가독성 위해 분리)
 */

export const BUDGET_PRESETS = [
  { label: "전체", min: "", max: "" },
  { label: "1억 미만", min: "", max: "99999999" },
  { label: "1억~5억", min: "100000000", max: "499999999" },
  { label: "5억~10억", min: "500000000", max: "999999999" },
  { label: "10억 이상", min: "1000000000", max: "" },
] as const;

export type RegionItem = { code: string; label: string; type: "province" | "city" };

export const REGION_GROUPS: { label: string; items: RegionItem[] }[] = [
  { label: "서울", items: [
    { code: "서울", label: "서울특별시 전체", type: "province" },
    { code: "강남구", label: "강남구", type: "city" },
    { code: "강동구", label: "강동구", type: "city" },
    { code: "강북구", label: "강북구", type: "city" },
    { code: "강서구", label: "강서구(서울)", type: "city" },
    { code: "관악구", label: "관악구", type: "city" },
    { code: "광진구", label: "광진구", type: "city" },
    { code: "구로구", label: "구로구", type: "city" },
    { code: "금천구", label: "금천구", type: "city" },
    { code: "노원구", label: "노원구", type: "city" },
    { code: "도봉구", label: "도봉구", type: "city" },
    { code: "동대문구", label: "동대문구", type: "city" },
    { code: "동작구", label: "동작구", type: "city" },
    { code: "마포구", label: "마포구", type: "city" },
    { code: "서대문구", label: "서대문구", type: "city" },
    { code: "서초구", label: "서초구", type: "city" },
    { code: "성동구", label: "성동구", type: "city" },
    { code: "성북구", label: "성북구", type: "city" },
    { code: "송파구", label: "송파구", type: "city" },
    { code: "양천구", label: "양천구", type: "city" },
    { code: "영등포구", label: "영등포구", type: "city" },
    { code: "용산구", label: "용산구", type: "city" },
    { code: "은평구", label: "은평구", type: "city" },
    { code: "종로구", label: "종로구", type: "city" },
    { code: "중구", label: "중구(서울)", type: "city" },
    { code: "중랑구", label: "중랑구", type: "city" },
  ]},
  { label: "경기·인천", items: [
    { code: "경기", label: "경기도 전체", type: "province" },
    { code: "수원시", label: "수원시", type: "city" },
    { code: "성남시", label: "성남시", type: "city" },
    { code: "용인시", label: "용인시", type: "city" },
    { code: "고양시", label: "고양시", type: "city" },
    { code: "화성시", label: "화성시", type: "city" },
    { code: "안산시", label: "안산시", type: "city" },
    { code: "평택시", label: "평택시", type: "city" },
    { code: "남양주시", label: "남양주시", type: "city" },
    { code: "안양시", label: "안양시", type: "city" },
    { code: "의정부시", label: "의정부시", type: "city" },
    { code: "부천시", label: "부천시", type: "city" },
    { code: "시흥시", label: "시흥시", type: "city" },
    { code: "파주시", label: "파주시", type: "city" },
    { code: "광명시", label: "광명시", type: "city" },
    { code: "하남시", label: "하남시", type: "city" },
    { code: "김포시", label: "김포시", type: "city" },
    { code: "구리시", label: "구리시", type: "city" },
    { code: "오산시", label: "오산시", type: "city" },
    { code: "군포시", label: "군포시", type: "city" },
    { code: "의왕시", label: "의왕시", type: "city" },
    { code: "이천시", label: "이천시", type: "city" },
    { code: "안성시", label: "안성시", type: "city" },
    { code: "광주시", label: "광주시(경기)", type: "city" },
    { code: "양주시", label: "양주시", type: "city" },
    { code: "포천시", label: "포천시", type: "city" },
    { code: "동두천시", label: "동두천시", type: "city" },
    { code: "과천시", label: "과천시", type: "city" },
    { code: "가평군", label: "가평군", type: "city" },
    { code: "양평군", label: "양평군", type: "city" },
    { code: "연천군", label: "연천군", type: "city" },
    { code: "인천", label: "인천광역시 전체", type: "province" },
    { code: "중구", label: "중구(인천)", type: "city" },
    { code: "동구", label: "동구(인천)", type: "city" },
    { code: "미추홀구", label: "미추홀구", type: "city" },
    { code: "연수구", label: "연수구", type: "city" },
    { code: "남동구", label: "남동구", type: "city" },
    { code: "부평구", label: "부평구", type: "city" },
    { code: "계양구", label: "계양구", type: "city" },
    { code: "서구", label: "서구(인천)", type: "city" },
    { code: "강화군", label: "강화군", type: "city" },
    { code: "옹진군", label: "옹진군", type: "city" },
  ]},
  { label: "충청권", items: [
    { code: "대전", label: "대전광역시 전체", type: "province" },
    { code: "동구", label: "동구(대전)", type: "city" },
    { code: "중구", label: "중구(대전)", type: "city" },
    { code: "서구", label: "서구(대전)", type: "city" },
    { code: "유성구", label: "유성구", type: "city" },
    { code: "대덕구", label: "대덕구", type: "city" },
    { code: "세종", label: "세종특별자치시", type: "province" },
    { code: "충북", label: "충청북도 전체", type: "province" },
    { code: "청주시", label: "청주시", type: "city" },
    { code: "충주시", label: "충주시", type: "city" },
    { code: "제천시", label: "제천시", type: "city" },
    { code: "보은군", label: "보은군", type: "city" },
    { code: "옥천군", label: "옥천군", type: "city" },
    { code: "영동군", label: "영동군", type: "city" },
    { code: "증평군", label: "증평군", type: "city" },
    { code: "진천군", label: "진천군", type: "city" },
    { code: "괴산군", label: "괴산군", type: "city" },
    { code: "음성군", label: "음성군", type: "city" },
    { code: "단양군", label: "단양군", type: "city" },
    { code: "충남", label: "충청남도 전체", type: "province" },
    { code: "천안시", label: "천안시", type: "city" },
    { code: "아산시", label: "아산시", type: "city" },
    { code: "공주시", label: "공주시", type: "city" },
    { code: "보령시", label: "보령시", type: "city" },
    { code: "서산시", label: "서산시", type: "city" },
    { code: "논산시", label: "논산시", type: "city" },
    { code: "계룡시", label: "계룡시", type: "city" },
    { code: "당진시", label: "당진시", type: "city" },
    { code: "금산군", label: "금산군", type: "city" },
    { code: "부여군", label: "부여군", type: "city" },
    { code: "서천군", label: "서천군", type: "city" },
    { code: "청양군", label: "청양군", type: "city" },
    { code: "홍성군", label: "홍성군", type: "city" },
    { code: "예산군", label: "예산군", type: "city" },
    { code: "태안군", label: "태안군", type: "city" },
  ]},
  { label: "전라권", items: [
    { code: "광주", label: "광주광역시 전체", type: "province" },
    { code: "동구", label: "동구(광주)", type: "city" },
    { code: "서구", label: "서구(광주)", type: "city" },
    { code: "남구", label: "남구(광주)", type: "city" },
    { code: "북구", label: "북구(광주)", type: "city" },
    { code: "광산구", label: "광산구", type: "city" },
    { code: "전북", label: "전북특별자치도 전체", type: "province" },
    { code: "전주시", label: "전주시", type: "city" },
    { code: "익산시", label: "익산시", type: "city" },
    { code: "군산시", label: "군산시", type: "city" },
    { code: "정읍시", label: "정읍시", type: "city" },
    { code: "남원시", label: "남원시", type: "city" },
    { code: "김제시", label: "김제시", type: "city" },
    { code: "완주군", label: "완주군", type: "city" },
    { code: "진안군", label: "진안군", type: "city" },
    { code: "무주군", label: "무주군", type: "city" },
    { code: "장수군", label: "장수군", type: "city" },
    { code: "임실군", label: "임실군", type: "city" },
    { code: "순창군", label: "순창군", type: "city" },
    { code: "고창군", label: "고창군", type: "city" },
    { code: "부안군", label: "부안군", type: "city" },
    { code: "전남", label: "전라남도 전체", type: "province" },
    { code: "여수시", label: "여수시", type: "city" },
    { code: "순천시", label: "순천시", type: "city" },
    { code: "목포시", label: "목포시", type: "city" },
    { code: "나주시", label: "나주시", type: "city" },
    { code: "광양시", label: "광양시", type: "city" },
    { code: "담양군", label: "담양군", type: "city" },
    { code: "곡성군", label: "곡성군", type: "city" },
    { code: "구례군", label: "구례군", type: "city" },
    { code: "고흥군", label: "고흥군", type: "city" },
    { code: "보성군", label: "보성군", type: "city" },
    { code: "화순군", label: "화순군", type: "city" },
    { code: "장흥군", label: "장흥군", type: "city" },
    { code: "강진군", label: "강진군", type: "city" },
    { code: "해남군", label: "해남군", type: "city" },
    { code: "영암군", label: "영암군", type: "city" },
    { code: "무안군", label: "무안군", type: "city" },
    { code: "함평군", label: "함평군", type: "city" },
    { code: "영광군", label: "영광군", type: "city" },
    { code: "장성군", label: "장성군", type: "city" },
    { code: "완도군", label: "완도군", type: "city" },
    { code: "진도군", label: "진도군", type: "city" },
    { code: "신안군", label: "신안군", type: "city" },
  ]},
  { label: "경상권", items: [
    { code: "부산", label: "부산광역시 전체", type: "province" },
    { code: "중구", label: "중구(부산)", type: "city" },
    { code: "서구", label: "서구(부산)", type: "city" },
    { code: "동구", label: "동구(부산)", type: "city" },
    { code: "남구", label: "남구(부산)", type: "city" },
    { code: "북구", label: "북구(부산)", type: "city" },
    { code: "강서구", label: "강서구(부산)", type: "city" },
    { code: "부산진구", label: "부산진구", type: "city" },
    { code: "해운대구", label: "해운대구", type: "city" },
    { code: "사하구", label: "사하구", type: "city" },
    { code: "금정구", label: "금정구", type: "city" },
    { code: "동래구", label: "동래구", type: "city" },
    { code: "연제구", label: "연제구", type: "city" },
    { code: "수영구", label: "수영구", type: "city" },
    { code: "사상구", label: "사상구", type: "city" },
    { code: "영도구", label: "영도구", type: "city" },
    { code: "기장군", label: "기장군", type: "city" },
    { code: "대구", label: "대구광역시 전체", type: "province" },
    { code: "중구", label: "중구(대구)", type: "city" },
    { code: "동구", label: "동구(대구)", type: "city" },
    { code: "서구", label: "서구(대구)", type: "city" },
    { code: "남구", label: "남구(대구)", type: "city" },
    { code: "북구", label: "북구(대구)", type: "city" },
    { code: "수성구", label: "수성구", type: "city" },
    { code: "달서구", label: "달서구", type: "city" },
    { code: "달성군", label: "달성군", type: "city" },
    { code: "울산", label: "울산광역시 전체", type: "province" },
    { code: "중구", label: "중구(울산)", type: "city" },
    { code: "남구", label: "남구(울산)", type: "city" },
    { code: "동구", label: "동구(울산)", type: "city" },
    { code: "북구", label: "북구(울산)", type: "city" },
    { code: "울주군", label: "울주군", type: "city" },
    { code: "경북", label: "경상북도 전체", type: "province" },
    { code: "포항시", label: "포항시", type: "city" },
    { code: "구미시", label: "구미시", type: "city" },
    { code: "경주시", label: "경주시", type: "city" },
    { code: "안동시", label: "안동시", type: "city" },
    { code: "김천시", label: "김천시", type: "city" },
    { code: "영주시", label: "영주시", type: "city" },
    { code: "영천시", label: "영천시", type: "city" },
    { code: "상주시", label: "상주시", type: "city" },
    { code: "문경시", label: "문경시", type: "city" },
    { code: "경산시", label: "경산시", type: "city" },
    { code: "군위군", label: "군위군", type: "city" },
    { code: "의성군", label: "의성군", type: "city" },
    { code: "청송군", label: "청송군", type: "city" },
    { code: "영양군", label: "영양군", type: "city" },
    { code: "영덕군", label: "영덕군", type: "city" },
    { code: "청도군", label: "청도군", type: "city" },
    { code: "고령군", label: "고령군", type: "city" },
    { code: "성주군", label: "성주군", type: "city" },
    { code: "칠곡군", label: "칠곡군", type: "city" },
    { code: "예천군", label: "예천군", type: "city" },
    { code: "봉화군", label: "봉화군", type: "city" },
    { code: "울진군", label: "울진군", type: "city" },
    { code: "울릉군", label: "울릉군", type: "city" },
    { code: "경남", label: "경상남도 전체", type: "province" },
    { code: "창원시", label: "창원시", type: "city" },
    { code: "진주시", label: "진주시", type: "city" },
    { code: "김해시", label: "김해시", type: "city" },
    { code: "통영시", label: "통영시", type: "city" },
    { code: "사천시", label: "사천시", type: "city" },
    { code: "밀양시", label: "밀양시", type: "city" },
    { code: "거제시", label: "거제시", type: "city" },
    { code: "양산시", label: "양산시", type: "city" },
    { code: "의령군", label: "의령군", type: "city" },
    { code: "함안군", label: "함안군", type: "city" },
    { code: "창녕군", label: "창녕군", type: "city" },
    { code: "고성군", label: "고성군(경남)", type: "city" },
    { code: "남해군", label: "남해군", type: "city" },
    { code: "하동군", label: "하동군", type: "city" },
    { code: "산청군", label: "산청군", type: "city" },
    { code: "함양군", label: "함양군", type: "city" },
    { code: "거창군", label: "거창군", type: "city" },
    { code: "합천군", label: "합천군", type: "city" },
  ]},
  { label: "강원/제주", items: [
    { code: "강원", label: "강원특별자치도 전체", type: "province" },
    { code: "춘천시", label: "춘천시", type: "city" },
    { code: "원주시", label: "원주시", type: "city" },
    { code: "강릉시", label: "강릉시", type: "city" },
    { code: "동해시", label: "동해시", type: "city" },
    { code: "태백시", label: "태백시", type: "city" },
    { code: "속초시", label: "속초시", type: "city" },
    { code: "삼척시", label: "삼척시", type: "city" },
    { code: "홍천군", label: "홍천군", type: "city" },
    { code: "횡성군", label: "횡성군", type: "city" },
    { code: "영월군", label: "영월군", type: "city" },
    { code: "평창군", label: "평창군", type: "city" },
    { code: "정선군", label: "정선군", type: "city" },
    { code: "철원군", label: "철원군", type: "city" },
    { code: "화천군", label: "화천군", type: "city" },
    { code: "양구군", label: "양구군", type: "city" },
    { code: "인제군", label: "인제군", type: "city" },
    { code: "고성군", label: "고성군(강원)", type: "city" },
    { code: "양양군", label: "양양군", type: "city" },
    { code: "제주", label: "제주특별자치도 전체", type: "province" },
    { code: "제주시", label: "제주시", type: "city" },
    { code: "서귀포시", label: "서귀포시", type: "city" },
  ]},
];
